### ISSUE TITLE
Implementation of text component generation shortcuts.

### ISSUE THREAD

**Issue by Xemiru** [Xemiru/Undertailor#19]
No one probably likes writing a giant block of ass over and over just for simple lines of text.

As in, 

```lua
text.fromString("[font=8bitop]", "[color=#FFFFFF]I [color=#FFFFFF]AM [color=#FFFFFF]A [color=#FFFFFF]WHITE RAINBOW")
```

is better than

```lua
local txt = text.newText("8bitop")
txt:addComponent(text.component.newComponent("I ", nil, colors.fromHex("#FFFFFF")))
txt:addComponent(text.component.newComponent("AM ", nil, colors.fromHex("#FFFFFF")))
txt:addComponent(text.component.newComponent("A ", nil, colors.fromHex("#FFFFFF")))
txt:addComponent(text.component.newComponent("WHITE RAINBOW", nil, colors.fromHex("#FFFFFF")))
```

Implementation of this system should leave the user with an option to make their cutscene dialog editing easier by looking at one string instead of 17 lines.

Possible parameters include all currently available, which are

- `[font=8bitop]` (string)
- `[style=swimmyworm]` (string)
- `[color=#482838]` (string) OR `[color=255,255,255]` (3 ints)
- `[speed=75]` (int)
- `[sound=voice.character]` (string)
- `[delay=1.5]` (number)

This system should be able to also let the user continue using brackets normally without it being confused for parameter instantiation. That is,

`[param1=a][param1=a][param1=a]\[ohlookabracket[param1=a]` should return me the grouped parameters `[param1=a][param1=a][param1=a]`, and `[param1=a]`, ignoring `\[ohlookabracket`.

As for the implementation of the final function, the final function should be able to turn one whole string into a single text object with a set amount of components linked to parameters laid out in the string. Each time a new group of parameters is encountered, a new component should be made. Default parameters can be set to default to if a parameter isn't specified.

`text.fromString("[font=8bitop]", "[color=#121234]im colored [color=#124544][style=swimmyworm]im colored and styled [sound=voice.char]\[i have brackets and a voice\]")`

should be equivalent to

```lua
local txt = text.newText("8bitop")
txt:addComponents(
    text.component.newComponent("im colored", nil, nil, color.fromHex("#121234")),
    text.component.newComponent("im colored and styled", nil, "swimmyworm", color.fromHex("#124544")),
    text.component.newComponent("[i have brackets and a voice]", nil, nil, nil, "voice.char"),
)
```

**Comment by FerusGrim** [comment]
I'll work on this while I'm internet-less, today. Push tonight? <3
